### ISSUE TITLE
如何正确升级版本？

### ISSUE THREAD

**Issue by tgabc** [cym1102/svnWebUI#1]
我准备把我这里的1.1.0容器版本升级到最新版本1.3.3，但是直接升级后发现数据库从sqllite自动切换到h2了，读取不到上一版本的数据，因此我暂时终止了我的操作，目前准备先把1.1.0转换到外部MySQL使用，再进行后续升级。比较头疼的是1.1.0版本不能正确使用环境变量${BOOT_OPTIONS}指向我新建的MySQL，所以应该如何正确升级版本1.1.0到1.3.3？
![image](https://user-images.githubusercontent.com/49581225/152906440-f37c3f81-286b-4c03-aba7-ffb81201da70.png)

**Comment by cym1102** [comment]
早期版本选用sqlite, 后来发现无法在arm alpine上使用, 就换成h2了, 但没想到早期版本还有用户在使用.
用户和小组可以依靠导入passwd和authz文件实现, 仓库可以直接扫描已存在的仓库实现导入. 也许这些功能可以帮到你. 然后你需要重新分配仓库权限


&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/svnWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 上午10:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/svnWebUI] 如何正确升级版本？ (Issue #1)





 
我准备把我这里的1.1.0容器版本升级到最新版本1.3.3，但是直接升级后发现数据库从sqllite自动切换到h2了，读取不到上一版本的数据，因此我暂时终止了我的操作，目前准备先把1.1.0转换到外部MySQL使用，再进行后续升级。比较头疼的是1.1.0版本不能正确使用环境变量${BOOT_OPTIONS}指向我新建的MySQL，所以应该如何正确升级版本1.1.0到1.3.3？
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tgabc** [comment]
感谢回复，问题现在解决了：我另外新建了一个1.3.3的服务可以正常连接MySQL，通过导出1.1.0版本项目的sqllite的sql文件，筛选出insert语句到MySQL修改执行就可以切过去了，剩下的svn迁移我直接物理覆盖目录也都搞定了
