### ISSUE TITLE
文件/home/svnWebUI/repo/passwd中的用户名及密码是明文

### ISSUE THREAD

**Issue by besonzore** [cym1102/svnWebUI#11]
-------------------------------------------------------------
/home/svnWebUI/repo/passwd的内容
[users]
svnWebUI = d6e03a64-6cbc-40f1-9ca5-7b316bd605d1
user = 123456
-------------------------------------------------------------
所有密码都是明文【作为服务器，非常不安全】

-------------------------------------------------------------
/home/svnWebUI/repo/httpdPasswd的内容
[users]
svnWebUI:$apr1$ydfeD.xp$Eycy0CYnQAHrndw3oJDBB1
user:$apr1$l9zIbJPF$YVuPK4UMv9hawu6VPbooz0
-------------------------------------------------------------
【httpdPasswd文件OK】

建议去掉svn://xxx.xxx.xxx.xxx/test协议的支持
仅保留有密码验证的http://xxx.xxx.xxx.xxx/test的协议支持
即仅使用httpdPasswd进行密码验证

**Comment by cym1102** [comment]
http协议不支持大文件上传, 有些大于4G的文件传不上去, svn是个很古老的软件了, 他的默认密码保存就是这样的. 



***@***.***
 
发件人： besonzore
发送时间： 2024-07-01 17:25
收件人： cym1102/svnWebUI
抄送： Subscribed
主题： [cym1102/svnWebUI] 文件/home/svnWebUI/repo/passwd中的用户名及密码是明文 (Issue #11)


/home/svnWebUI/repo/passwd的内容
[users]
svnWebUI = d6e03a64-6cbc-40f1-9ca5-7b316bd605d1
user = 123456
所有密码都是明文【作为服务器，非常不安全】


/home/svnWebUI/repo/httpdPasswd的内容
[users]
svnWebUI:$apr1$ydfeD.xp$Eycy0CYnQAHrndw3oJDBB1
user:$apr1$l9zIbJPF$YVuPK4UMv9hawu6VPbooz0
【httpdPasswd文件OK】
建议去掉svn://xxx.xxx.xxx.xxx/test协议的支持
仅保留有密码验证的http://xxx.xxx.xxx.xxx/test的协议支持
即仅使用httpdPasswd进行密码验证
