### ISSUE TITLE
增加https协议的支持

### ISSUE THREAD

**Issue by besonzore** [cym1102/svnWebUI#12]

**Comment by besonzore** [comment]
使用docker image
仅有svn 和 http 两种协议
建议增加https的协议，以便提高server及密码的安全性

**Comment by cym1102** [comment]
https请使用nginxWebUI部署ssl证书



***@***.***
 
发件人： besonzore
发送时间： 2024-07-01 17:37
收件人： cym1102/svnWebUI
抄送： Subscribed
主题： Re: [cym1102/svnWebUI] 增加https协议的支持 (Issue #12)
使用docker image
仅有svn 和 http 两种协议
建议增加https的协议，以便提高server及密码的安全性
