### ISSUE TITLE
已有的SVN库能导入吗

### ISSUE THREAD

**Issue by Blackson15** [cym1102/svnWebUI#4]

**Comment by cym1102** [comment]
可以导入, 把库移动到/home/svnWebUI/repo下, 再到页面导入已存在的库

**Comment by zaco-chen** [comment]
您好，請問現在還是要用把庫移到/home/svnWebUI/repo下的方式處理嗎?
還是說可以使用參數 --project.home 來解決呢?
謝謝!

**Comment by cym1102** [comment]
--project.home 指定的是程序使用的数据的目录, 其他仓库必须移动到project.home/repo下才能导入webui进行管理



***@***.***
 
发件人： zaco-chen
发送时间： 2024-09-19 15:28
收件人： cym1102/svnWebUI
抄送： cym1102; State change
主题： Re: [cym1102/svnWebUI] 已有的SVN库能导入吗 (Issue #4)
您好，請問現在還是要用把庫移到/home/svnWebUI/repo下的方式處理嗎?
還是說可以使用參數 --project.home 來解決呢?
謝謝!
