### ISSUE TITLE
1.7.7版本中没有导入备份功能

### ISSUE THREAD

**Issue by Larpx** [cym1102/svnWebUI#6]
请问1.7.7版本中没有导入备份功能吗

**Comment by cym1102** [comment]
有啊, 就在系统配置页面里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/svnWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 晚上11:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/svnWebUI] 1.7.7版本中没有导入备份功能 (Issue #6)





 
请问1.7.7版本中没有导入备份功能吗

**Comment by Larpx** [comment]
不好意思，是我表述错了，是仓库的备份恢复功能，我看演示网站是有的，但是自己部署了1.7.7版本发型没有这个功能
![image](https://user-images.githubusercontent.com/12372858/221867039-eb08079c-ba3b-4b0e-8aa3-3ccc9f761ab0.png)

**Comment by cym1102** [comment]
这个功能已经舍弃了, 通过http执行备份有很多问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月28日(星期二) 晚上9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/svnWebUI] 1.7.7版本中没有导入备份功能 (Issue #6)





 
不好意思，是我表述错了，是仓库的备份恢复功能，我看演示网站是有的，但是自己部署了1.7.7版本发型没有这个功能

**Comment by Larpx** [comment]
好的好的，直接使用命令还原备份了，谢谢回复
