### ISSUE TITLE
我把管理员删除了，现在怎么给这个账户添加新的管理员？

### ISSUE THREAD

**Issue by tetejm** [cym1102/svnWebUI#7]

**Comment by cym1102** [comment]
把h2数据库文件拿出来，用dbwear写进去一个管理员



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月10日(周五) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/svnWebUI] 我把管理员删除了，现在怎么给这个账户添加新的管理员？ (Issue #7)
